### PR TITLE
Strong mode compliance.

### PR DESCRIPTION
**Pull request by vadimtsushko**
Hi Greg. I've tried to move repo to strong mode. Changed most db tests to async await syntax too (apparently it simplest way to adapt these to strong mode). Please look at it.

### CODE REVIEW

**Comment by xxgreg** [comment]
Looks good. Since the rest of the code isn't strong mode compliant yet, can you remove the .analysis_options setting, and then I'll merge the rest of the changes.

Cheers!

**Comment by vadimtsushko** [comment]
Done. BTW, what is the rest of the code that is not strong mode compliant? You mean code in the different packages?

**Comment by vadimtsushko** [comment]
I've made another pull request with options removed. https://github.com/xxgreg/dart_postgresql/pull/84

**Comment by xxgreg** [comment]
Yes this patch cleans up the tests. But I think lib/postgresql.dart, and lib/pool.dart, are still not strong mode clean.

I checked out the branch, and ran dartanalyzer lib/postgresql.dart, and got a screen full of errors.

I appreciate you taking the time to do this.

I'm rather busy, so just doing minimal maintenance.

I also notice there is work going on here: https://github.com/stablekernel/postgresql-dart

Not sure if they have a stable release yet, but it's probably also worth a shot if you need the code to be strong mode clean.

**Comment by vadimtsushko** [comment]
Thank you.

**Pull request closed without merging**
